package com.ule.uhj.app.zgd.dao;

import com.ule.uhj.app.zgd.model.SaleActRegion;
import com.ule.uhj.app.zgd.model.SaleActRegionExample;
import com.ule.uhj.app.zgd.model.SaleActRegionKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaleActRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_REGION
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    int countByExample(SaleActRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_REGION
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    int deleteByExample(SaleActRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_REGION
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    int deleteByPrimaryKey(SaleActRegionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_REGION
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    int insert(SaleActRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_REGION
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    int insertSelective(SaleActRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_REGION
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    List<SaleActRegion> selectByExample(SaleActRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_REGION
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    SaleActRegion selectByPrimaryKey(SaleActRegionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_REGION
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    int updateByExampleSelective(@Param("record") SaleActRegion record, @Param("example") SaleActRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_REGION
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    int updateByExample(@Param("record") SaleActRegion record, @Param("example") SaleActRegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_REGION
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    int updateByPrimaryKeySelective(SaleActRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_REGION
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    int updateByPrimaryKey(SaleActRegion record);
}