package com.ule.uhj.app.zgd.model;

import java.math.BigDecimal;

public class AutoRepaySettingInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_AUTO_REPAY_SETTING.ID
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_AUTO_REPAY_SETTING.USER_ONLY_ID
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    private String userOnlyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_AUTO_REPAY_SETTING.AMOUNT
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_AUTO_REPAY_SETTING.STATE
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_AUTO_REPAY_SETTING.CREATE_USER
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_AUTO_REPAY_SETTING.CREATE_TIME
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_AUTO_REPAY_SETTING.UPDATE_USER
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_AUTO_REPAY_SETTING.UPDATE_TIME
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_AUTO_REPAY_SETTING.ID
     *
     * @return the value of T_J_AUTO_REPAY_SETTING.ID
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_AUTO_REPAY_SETTING.ID
     *
     * @param id the value for T_J_AUTO_REPAY_SETTING.ID
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_AUTO_REPAY_SETTING.USER_ONLY_ID
     *
     * @return the value of T_J_AUTO_REPAY_SETTING.USER_ONLY_ID
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    public String getUserOnlyId() {
        return userOnlyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_AUTO_REPAY_SETTING.USER_ONLY_ID
     *
     * @param userOnlyId the value for T_J_AUTO_REPAY_SETTING.USER_ONLY_ID
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    public void setUserOnlyId(String userOnlyId) {
        this.userOnlyId = userOnlyId == null ? null : userOnlyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_AUTO_REPAY_SETTING.AMOUNT
     *
     * @return the value of T_J_AUTO_REPAY_SETTING.AMOUNT
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_AUTO_REPAY_SETTING.AMOUNT
     *
     * @param amount the value for T_J_AUTO_REPAY_SETTING.AMOUNT
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_AUTO_REPAY_SETTING.STATE
     *
     * @return the value of T_J_AUTO_REPAY_SETTING.STATE
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_AUTO_REPAY_SETTING.STATE
     *
     * @param state the value for T_J_AUTO_REPAY_SETTING.STATE
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_AUTO_REPAY_SETTING.CREATE_USER
     *
     * @return the value of T_J_AUTO_REPAY_SETTING.CREATE_USER
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_AUTO_REPAY_SETTING.CREATE_USER
     *
     * @param createUser the value for T_J_AUTO_REPAY_SETTING.CREATE_USER
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_AUTO_REPAY_SETTING.CREATE_TIME
     *
     * @return the value of T_J_AUTO_REPAY_SETTING.CREATE_TIME
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_AUTO_REPAY_SETTING.CREATE_TIME
     *
     * @param createTime the value for T_J_AUTO_REPAY_SETTING.CREATE_TIME
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_AUTO_REPAY_SETTING.UPDATE_USER
     *
     * @return the value of T_J_AUTO_REPAY_SETTING.UPDATE_USER
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_AUTO_REPAY_SETTING.UPDATE_USER
     *
     * @param updateUser the value for T_J_AUTO_REPAY_SETTING.UPDATE_USER
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_AUTO_REPAY_SETTING.UPDATE_TIME
     *
     * @return the value of T_J_AUTO_REPAY_SETTING.UPDATE_TIME
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_AUTO_REPAY_SETTING.UPDATE_TIME
     *
     * @param updateTime the value for T_J_AUTO_REPAY_SETTING.UPDATE_TIME
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}