package com.ule.uhj.app.zgd.dao;

import com.ule.uhj.app.zgd.model.AutoRepayLogInfo;
import com.ule.uhj.app.zgd.model.AutoRepayLogInfoExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AutoRepayLogInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_LOG
     *
     * @mbggenerated Thu Apr 12 15:31:02 CST 2018
     */
    int countByExample(AutoRepayLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_LOG
     *
     * @mbggenerated Thu Apr 12 15:31:02 CST 2018
     */
    int deleteByExample(AutoRepayLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_LOG
     *
     * @mbggenerated Thu Apr 12 15:31:02 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_LOG
     *
     * @mbggenerated Thu Apr 12 15:31:02 CST 2018
     */
    int insert(AutoRepayLogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_LOG
     *
     * @mbggenerated Thu Apr 12 15:31:02 CST 2018
     */
    int insertSelective(AutoRepayLogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_LOG
     *
     * @mbggenerated Thu Apr 12 15:31:02 CST 2018
     */
    List<AutoRepayLogInfo> selectByExample(AutoRepayLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_LOG
     *
     * @mbggenerated Thu Apr 12 15:31:02 CST 2018
     */
    AutoRepayLogInfo selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_LOG
     *
     * @mbggenerated Thu Apr 12 15:31:02 CST 2018
     */
    int updateByExampleSelective(@Param("record") AutoRepayLogInfo record, @Param("example") AutoRepayLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_LOG
     *
     * @mbggenerated Thu Apr 12 15:31:02 CST 2018
     */
    int updateByExample(@Param("record") AutoRepayLogInfo record, @Param("example") AutoRepayLogInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_LOG
     *
     * @mbggenerated Thu Apr 12 15:31:02 CST 2018
     */
    int updateByPrimaryKeySelective(AutoRepayLogInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_LOG
     *
     * @mbggenerated Thu Apr 12 15:31:02 CST 2018
     */
    int updateByPrimaryKey(AutoRepayLogInfo record);
}