server:
  port: 8081
  servlet:
    context-path: /te
  

# 数据库配置
spring:
  datasource:
    url:  jdbc:mysql://172.25.201.63:3306/internet_finance?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: uleapp_itfin
    password: itfin.2016!A
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
   # data: classpath:db/data.sql  脚本中初始化数据的预计
   # schema: classpath:db/schema.sql  脚本中创建表的语句
   # sql-script-encoding:   utf-8  设置脚本的编码
  thymeleaf:
    #是关闭 Thymeleaf 的缓存，不然在开发过程中修改页面不会立刻生效需要重启，生产可配置为 true。
    cache: false 
mybatis:
  mapper-locations: classpath:mapper/*.xml   #存放xml 文件的位置
  type-aliases-package: com.example.boot.entity #用于xml 实体类不再写类全名 只是洗个简单类名就可以了
            
