package com.ule.uhj.app.zgd.model;

public class ForecastWord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_FORECAST_WORD.CODE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_FORECAST_WORD.WORD
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    private String word;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_FORECAST_WORD.FORECAST_CODE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    private String forecastCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_FORECAST_WORD.CODE
     *
     * @return the value of T_J_FORECAST_WORD.CODE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_FORECAST_WORD.CODE
     *
     * @param code the value for T_J_FORECAST_WORD.CODE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_FORECAST_WORD.WORD
     *
     * @return the value of T_J_FORECAST_WORD.WORD
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_FORECAST_WORD.WORD
     *
     * @param word the value for T_J_FORECAST_WORD.WORD
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_FORECAST_WORD.FORECAST_CODE
     *
     * @return the value of T_J_FORECAST_WORD.FORECAST_CODE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    public String getForecastCode() {
        return forecastCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_FORECAST_WORD.FORECAST_CODE
     *
     * @param forecastCode the value for T_J_FORECAST_WORD.FORECAST_CODE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    public void setForecastCode(String forecastCode) {
        this.forecastCode = forecastCode == null ? null : forecastCode.trim();
    }
}