package com.ule.oracle.dao;

import com.ule.oracle.model.Constant;
import com.ule.oracle.model.ConstantExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConstantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CONSTANT
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    int countByExample(ConstantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CONSTANT
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    int deleteByExample(ConstantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CONSTANT
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CONSTANT
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    int insert(Constant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CONSTANT
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    int insertSelective(Constant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CONSTANT
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    List<Constant> selectByExample(ConstantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CONSTANT
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    Constant selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CONSTANT
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") Constant record, @Param("example") ConstantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CONSTANT
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    int updateByExample(@Param("record") Constant record, @Param("example") ConstantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CONSTANT
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    int updateByPrimaryKeySelective(Constant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CONSTANT
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    int updateByPrimaryKey(Constant record);
}