package com.ule.oracle.dao;

import com.ule.oracle.model.InterfaceRecord;
import com.ule.oracle.model.InterfaceRecordExample;
import com.ule.oracle.model.InterfaceRecordWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InterfaceRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_RECORD
     *
     * @mbggenerated Mon Apr 08 10:09:39 CST 2019
     */
    int countByExample(InterfaceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_RECORD
     *
     * @mbggenerated Mon Apr 08 10:09:39 CST 2019
     */
    int deleteByExample(InterfaceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_RECORD
     *
     * @mbggenerated Mon Apr 08 10:09:39 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_RECORD
     *
     * @mbggenerated Mon Apr 08 10:09:39 CST 2019
     */
    int insert(InterfaceRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_RECORD
     *
     * @mbggenerated Mon Apr 08 10:09:39 CST 2019
     */
    int insertSelective(InterfaceRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_RECORD
     *
     * @mbggenerated Mon Apr 08 10:09:39 CST 2019
     */
    List<InterfaceRecordWithBLOBs> selectByExampleWithBLOBs(InterfaceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_RECORD
     *
     * @mbggenerated Mon Apr 08 10:09:39 CST 2019
     */
    List<InterfaceRecord> selectByExample(InterfaceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_RECORD
     *
     * @mbggenerated Mon Apr 08 10:09:39 CST 2019
     */
    InterfaceRecordWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_RECORD
     *
     * @mbggenerated Mon Apr 08 10:09:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") InterfaceRecordWithBLOBs record, @Param("example") InterfaceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_RECORD
     *
     * @mbggenerated Mon Apr 08 10:09:39 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") InterfaceRecordWithBLOBs record, @Param("example") InterfaceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_RECORD
     *
     * @mbggenerated Mon Apr 08 10:09:39 CST 2019
     */
    int updateByExample(@Param("record") InterfaceRecord record, @Param("example") InterfaceRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_RECORD
     *
     * @mbggenerated Mon Apr 08 10:09:39 CST 2019
     */
    int updateByPrimaryKeySelective(InterfaceRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_RECORD
     *
     * @mbggenerated Mon Apr 08 10:09:39 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(InterfaceRecordWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_RECORD
     *
     * @mbggenerated Mon Apr 08 10:09:39 CST 2019
     */
    int updateByPrimaryKey(InterfaceRecord record);
}