package com.ule.uhj.app.zgd.dao;

import com.ule.uhj.app.zgd.model.SaleActInfo;
import com.ule.uhj.app.zgd.model.SaleActInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaleActInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    int countByExample(SaleActInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    int deleteByExample(SaleActInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    int insert(SaleActInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    int insertSelective(SaleActInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    List<SaleActInfo> selectByExample(SaleActInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    SaleActInfo selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    int updateByExampleSelective(@Param("record") SaleActInfo record, @Param("example") SaleActInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    int updateByExample(@Param("record") SaleActInfo record, @Param("example") SaleActInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    int updateByPrimaryKeySelective(SaleActInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    int updateByPrimaryKey(SaleActInfo record);
}