package com.ule.uhj.app.zgd.model;

public class ForecastScope {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_FORECAST_SCOPE.CODE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_FORECAST_SCOPE.BUSINESS_SCOPE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    private String businessScope;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_FORECAST_SCOPE.CODE
     *
     * @return the value of T_J_FORECAST_SCOPE.CODE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_FORECAST_SCOPE.CODE
     *
     * @param code the value for T_J_FORECAST_SCOPE.CODE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_FORECAST_SCOPE.BUSINESS_SCOPE
     *
     * @return the value of T_J_FORECAST_SCOPE.BUSINESS_SCOPE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    public String getBusinessScope() {
        return businessScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_FORECAST_SCOPE.BUSINESS_SCOPE
     *
     * @param businessScope the value for T_J_FORECAST_SCOPE.BUSINESS_SCOPE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    public void setBusinessScope(String businessScope) {
        this.businessScope = businessScope == null ? null : businessScope.trim();
    }
}