package com.ule.uhj.app.zgd.dao;

import com.ule.uhj.app.zgd.model.ForecastScopeVpsWord;
import com.ule.uhj.app.zgd.model.ForecastScopeVpsWordExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ForecastScopeVpsWordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE_VPS_WORD
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    int countByExample(ForecastScopeVpsWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE_VPS_WORD
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    int deleteByExample(ForecastScopeVpsWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE_VPS_WORD
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE_VPS_WORD
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    int insert(ForecastScopeVpsWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE_VPS_WORD
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    int insertSelective(ForecastScopeVpsWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE_VPS_WORD
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    List<ForecastScopeVpsWord> selectByExample(ForecastScopeVpsWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE_VPS_WORD
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    ForecastScopeVpsWord selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE_VPS_WORD
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") ForecastScopeVpsWord record, @Param("example") ForecastScopeVpsWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE_VPS_WORD
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    int updateByExample(@Param("record") ForecastScopeVpsWord record, @Param("example") ForecastScopeVpsWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE_VPS_WORD
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    int updateByPrimaryKeySelective(ForecastScopeVpsWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE_VPS_WORD
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    int updateByPrimaryKey(ForecastScopeVpsWord record);
}