package com.ule.uhj.app.zgd.model;

public class CustomerAccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_ACCOUNT.ID
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_ACCOUNT.USER_ONLY_ID
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    private String userOnlyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_ACCOUNT.CONTACT_ID
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    private String contactId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_ACCOUNT.BANK_NO
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    private String bankNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_ACCOUNT.BANK_NAME
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_ACCOUNT.SUBBRANCH_NO
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    private String subbranchNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_ACCOUNT.SUBBRANCH_NAME
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    private String subbranchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_ACCOUNT.ACCOUNT_NAME
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_ACCOUNT.ACCOUNT_NO
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    private String accountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_ACCOUNT.PHONE_NO
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_ACCOUNT.VALID_DATE
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    private String validDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_ACCOUNT.STATUS
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_ACCOUNT.ID
     *
     * @return the value of T_J_CUSTOMER_ACCOUNT.ID
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_ACCOUNT.ID
     *
     * @param id the value for T_J_CUSTOMER_ACCOUNT.ID
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_ACCOUNT.USER_ONLY_ID
     *
     * @return the value of T_J_CUSTOMER_ACCOUNT.USER_ONLY_ID
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public String getUserOnlyId() {
        return userOnlyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_ACCOUNT.USER_ONLY_ID
     *
     * @param userOnlyId the value for T_J_CUSTOMER_ACCOUNT.USER_ONLY_ID
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public void setUserOnlyId(String userOnlyId) {
        this.userOnlyId = userOnlyId == null ? null : userOnlyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_ACCOUNT.CONTACT_ID
     *
     * @return the value of T_J_CUSTOMER_ACCOUNT.CONTACT_ID
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public String getContactId() {
        return contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_ACCOUNT.CONTACT_ID
     *
     * @param contactId the value for T_J_CUSTOMER_ACCOUNT.CONTACT_ID
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public void setContactId(String contactId) {
        this.contactId = contactId == null ? null : contactId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_ACCOUNT.BANK_NO
     *
     * @return the value of T_J_CUSTOMER_ACCOUNT.BANK_NO
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_ACCOUNT.BANK_NO
     *
     * @param bankNo the value for T_J_CUSTOMER_ACCOUNT.BANK_NO
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_ACCOUNT.BANK_NAME
     *
     * @return the value of T_J_CUSTOMER_ACCOUNT.BANK_NAME
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_ACCOUNT.BANK_NAME
     *
     * @param bankName the value for T_J_CUSTOMER_ACCOUNT.BANK_NAME
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_ACCOUNT.SUBBRANCH_NO
     *
     * @return the value of T_J_CUSTOMER_ACCOUNT.SUBBRANCH_NO
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public String getSubbranchNo() {
        return subbranchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_ACCOUNT.SUBBRANCH_NO
     *
     * @param subbranchNo the value for T_J_CUSTOMER_ACCOUNT.SUBBRANCH_NO
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public void setSubbranchNo(String subbranchNo) {
        this.subbranchNo = subbranchNo == null ? null : subbranchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_ACCOUNT.SUBBRANCH_NAME
     *
     * @return the value of T_J_CUSTOMER_ACCOUNT.SUBBRANCH_NAME
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public String getSubbranchName() {
        return subbranchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_ACCOUNT.SUBBRANCH_NAME
     *
     * @param subbranchName the value for T_J_CUSTOMER_ACCOUNT.SUBBRANCH_NAME
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public void setSubbranchName(String subbranchName) {
        this.subbranchName = subbranchName == null ? null : subbranchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_ACCOUNT.ACCOUNT_NAME
     *
     * @return the value of T_J_CUSTOMER_ACCOUNT.ACCOUNT_NAME
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_ACCOUNT.ACCOUNT_NAME
     *
     * @param accountName the value for T_J_CUSTOMER_ACCOUNT.ACCOUNT_NAME
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_ACCOUNT.ACCOUNT_NO
     *
     * @return the value of T_J_CUSTOMER_ACCOUNT.ACCOUNT_NO
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_ACCOUNT.ACCOUNT_NO
     *
     * @param accountNo the value for T_J_CUSTOMER_ACCOUNT.ACCOUNT_NO
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo == null ? null : accountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_ACCOUNT.PHONE_NO
     *
     * @return the value of T_J_CUSTOMER_ACCOUNT.PHONE_NO
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_ACCOUNT.PHONE_NO
     *
     * @param phoneNo the value for T_J_CUSTOMER_ACCOUNT.PHONE_NO
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_ACCOUNT.VALID_DATE
     *
     * @return the value of T_J_CUSTOMER_ACCOUNT.VALID_DATE
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public String getValidDate() {
        return validDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_ACCOUNT.VALID_DATE
     *
     * @param validDate the value for T_J_CUSTOMER_ACCOUNT.VALID_DATE
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public void setValidDate(String validDate) {
        this.validDate = validDate == null ? null : validDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_ACCOUNT.STATUS
     *
     * @return the value of T_J_CUSTOMER_ACCOUNT.STATUS
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_ACCOUNT.STATUS
     *
     * @param status the value for T_J_CUSTOMER_ACCOUNT.STATUS
     *
     * @mbggenerated Fri Oct 27 15:39:49 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}