package com.ule.uhj.app.zgd.model;

import java.math.BigDecimal;

public class OrderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.ID
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.USER_ID
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.ORDER_TYPE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.ORDER_TIME
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.ORDER_AMOUNT
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private BigDecimal orderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.APPLY_IP
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String applyIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.REPAY_TYPE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String repayType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.LAST_REPAY_DATE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String lastRepayDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.PERIODS
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private Short periods;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.INTER_RATE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private BigDecimal interRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.OVERDUE_RATE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private BigDecimal overdueRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.STATUS
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.CONTRACT_VER
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String contractVer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.REVIEWOR
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String reviewor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.REVIEW_TIME
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String reviewTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.REVIEW_REMARK
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String reviewRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.LOANOR
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String loanor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.LOAN_TIME
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String loanTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.LOAN_AMOUNT
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private BigDecimal loanAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.CREATE_TIME
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.CREATOR
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.UPDATE_TIME
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.UPDATOR
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.REMARK
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.HOLDING_BANK
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String holdingBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.HOLDING_CARD_NO
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String holdingCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.ACC_TYPE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private Short accType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.PRD_CODE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private Integer prdCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.LOAN_ID
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String loanId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.LOAN_PROGRESS
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private Short loanProgress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.LOAN_CONTRACT_NO
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String loanContractNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.DUEBILL_NO
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String duebillNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.LEND_AMOUNT
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private BigDecimal lendAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.LEND_DATE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String lendDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.NET_CONTRACT_URL
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String netContractUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.REPAY_ACC_NAME
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String repayAccName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.REPAY_ACC_NO
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String repayAccNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.LOAN_RATE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private BigDecimal loanRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.OVERDUE_DAY
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private Short overdueDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.SERVICE_CHARGE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private BigDecimal serviceCharge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.IS_RECEIVED
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private Short isReceived;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.LOAN_LENGTH
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String loanLength;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.AVAIL_BALANCE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private BigDecimal availBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.YC_MESSAGE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String ycMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.DISCOUNT
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private BigDecimal discount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.FIXED_REPAY_DATE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private Short fixedRepayDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.ACTUAL_SETTLE_DATE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String actualSettleDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.PAY_ID
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String payId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.REAL_ORDER_ID
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String realOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.REAL_ORDER_AMOUNT
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private BigDecimal realOrderAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.PX_NO
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String pxNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_ORDER.LOAN_TYPE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    private String loanType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.ID
     *
     * @return the value of T_J_ORDER.ID
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.ID
     *
     * @param id the value for T_J_ORDER.ID
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.USER_ID
     *
     * @return the value of T_J_ORDER.USER_ID
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.USER_ID
     *
     * @param userId the value for T_J_ORDER.USER_ID
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.ORDER_TYPE
     *
     * @return the value of T_J_ORDER.ORDER_TYPE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.ORDER_TYPE
     *
     * @param orderType the value for T_J_ORDER.ORDER_TYPE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.ORDER_TIME
     *
     * @return the value of T_J_ORDER.ORDER_TIME
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.ORDER_TIME
     *
     * @param orderTime the value for T_J_ORDER.ORDER_TIME
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setOrderTime(String orderTime) {
        this.orderTime = orderTime == null ? null : orderTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.ORDER_AMOUNT
     *
     * @return the value of T_J_ORDER.ORDER_AMOUNT
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public BigDecimal getOrderAmount() {
        return orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.ORDER_AMOUNT
     *
     * @param orderAmount the value for T_J_ORDER.ORDER_AMOUNT
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setOrderAmount(BigDecimal orderAmount) {
        this.orderAmount = orderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.APPLY_IP
     *
     * @return the value of T_J_ORDER.APPLY_IP
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getApplyIp() {
        return applyIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.APPLY_IP
     *
     * @param applyIp the value for T_J_ORDER.APPLY_IP
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setApplyIp(String applyIp) {
        this.applyIp = applyIp == null ? null : applyIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.REPAY_TYPE
     *
     * @return the value of T_J_ORDER.REPAY_TYPE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getRepayType() {
        return repayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.REPAY_TYPE
     *
     * @param repayType the value for T_J_ORDER.REPAY_TYPE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setRepayType(String repayType) {
        this.repayType = repayType == null ? null : repayType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.LAST_REPAY_DATE
     *
     * @return the value of T_J_ORDER.LAST_REPAY_DATE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getLastRepayDate() {
        return lastRepayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.LAST_REPAY_DATE
     *
     * @param lastRepayDate the value for T_J_ORDER.LAST_REPAY_DATE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setLastRepayDate(String lastRepayDate) {
        this.lastRepayDate = lastRepayDate == null ? null : lastRepayDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.PERIODS
     *
     * @return the value of T_J_ORDER.PERIODS
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public Short getPeriods() {
        return periods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.PERIODS
     *
     * @param periods the value for T_J_ORDER.PERIODS
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setPeriods(Short periods) {
        this.periods = periods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.INTER_RATE
     *
     * @return the value of T_J_ORDER.INTER_RATE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public BigDecimal getInterRate() {
        return interRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.INTER_RATE
     *
     * @param interRate the value for T_J_ORDER.INTER_RATE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setInterRate(BigDecimal interRate) {
        this.interRate = interRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.OVERDUE_RATE
     *
     * @return the value of T_J_ORDER.OVERDUE_RATE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public BigDecimal getOverdueRate() {
        return overdueRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.OVERDUE_RATE
     *
     * @param overdueRate the value for T_J_ORDER.OVERDUE_RATE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setOverdueRate(BigDecimal overdueRate) {
        this.overdueRate = overdueRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.STATUS
     *
     * @return the value of T_J_ORDER.STATUS
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.STATUS
     *
     * @param status the value for T_J_ORDER.STATUS
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.CONTRACT_VER
     *
     * @return the value of T_J_ORDER.CONTRACT_VER
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getContractVer() {
        return contractVer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.CONTRACT_VER
     *
     * @param contractVer the value for T_J_ORDER.CONTRACT_VER
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setContractVer(String contractVer) {
        this.contractVer = contractVer == null ? null : contractVer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.REVIEWOR
     *
     * @return the value of T_J_ORDER.REVIEWOR
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getReviewor() {
        return reviewor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.REVIEWOR
     *
     * @param reviewor the value for T_J_ORDER.REVIEWOR
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setReviewor(String reviewor) {
        this.reviewor = reviewor == null ? null : reviewor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.REVIEW_TIME
     *
     * @return the value of T_J_ORDER.REVIEW_TIME
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getReviewTime() {
        return reviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.REVIEW_TIME
     *
     * @param reviewTime the value for T_J_ORDER.REVIEW_TIME
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setReviewTime(String reviewTime) {
        this.reviewTime = reviewTime == null ? null : reviewTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.REVIEW_REMARK
     *
     * @return the value of T_J_ORDER.REVIEW_REMARK
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getReviewRemark() {
        return reviewRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.REVIEW_REMARK
     *
     * @param reviewRemark the value for T_J_ORDER.REVIEW_REMARK
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setReviewRemark(String reviewRemark) {
        this.reviewRemark = reviewRemark == null ? null : reviewRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.LOANOR
     *
     * @return the value of T_J_ORDER.LOANOR
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getLoanor() {
        return loanor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.LOANOR
     *
     * @param loanor the value for T_J_ORDER.LOANOR
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setLoanor(String loanor) {
        this.loanor = loanor == null ? null : loanor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.LOAN_TIME
     *
     * @return the value of T_J_ORDER.LOAN_TIME
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getLoanTime() {
        return loanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.LOAN_TIME
     *
     * @param loanTime the value for T_J_ORDER.LOAN_TIME
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setLoanTime(String loanTime) {
        this.loanTime = loanTime == null ? null : loanTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.LOAN_AMOUNT
     *
     * @return the value of T_J_ORDER.LOAN_AMOUNT
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public BigDecimal getLoanAmount() {
        return loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.LOAN_AMOUNT
     *
     * @param loanAmount the value for T_J_ORDER.LOAN_AMOUNT
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setLoanAmount(BigDecimal loanAmount) {
        this.loanAmount = loanAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.CREATE_TIME
     *
     * @return the value of T_J_ORDER.CREATE_TIME
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.CREATE_TIME
     *
     * @param createTime the value for T_J_ORDER.CREATE_TIME
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.CREATOR
     *
     * @return the value of T_J_ORDER.CREATOR
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.CREATOR
     *
     * @param creator the value for T_J_ORDER.CREATOR
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.UPDATE_TIME
     *
     * @return the value of T_J_ORDER.UPDATE_TIME
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.UPDATE_TIME
     *
     * @param updateTime the value for T_J_ORDER.UPDATE_TIME
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.UPDATOR
     *
     * @return the value of T_J_ORDER.UPDATOR
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.UPDATOR
     *
     * @param updator the value for T_J_ORDER.UPDATOR
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.REMARK
     *
     * @return the value of T_J_ORDER.REMARK
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.REMARK
     *
     * @param remark the value for T_J_ORDER.REMARK
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.HOLDING_BANK
     *
     * @return the value of T_J_ORDER.HOLDING_BANK
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getHoldingBank() {
        return holdingBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.HOLDING_BANK
     *
     * @param holdingBank the value for T_J_ORDER.HOLDING_BANK
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setHoldingBank(String holdingBank) {
        this.holdingBank = holdingBank == null ? null : holdingBank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.HOLDING_CARD_NO
     *
     * @return the value of T_J_ORDER.HOLDING_CARD_NO
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getHoldingCardNo() {
        return holdingCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.HOLDING_CARD_NO
     *
     * @param holdingCardNo the value for T_J_ORDER.HOLDING_CARD_NO
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setHoldingCardNo(String holdingCardNo) {
        this.holdingCardNo = holdingCardNo == null ? null : holdingCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.ACC_TYPE
     *
     * @return the value of T_J_ORDER.ACC_TYPE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public Short getAccType() {
        return accType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.ACC_TYPE
     *
     * @param accType the value for T_J_ORDER.ACC_TYPE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setAccType(Short accType) {
        this.accType = accType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.PRD_CODE
     *
     * @return the value of T_J_ORDER.PRD_CODE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public Integer getPrdCode() {
        return prdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.PRD_CODE
     *
     * @param prdCode the value for T_J_ORDER.PRD_CODE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setPrdCode(Integer prdCode) {
        this.prdCode = prdCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.LOAN_ID
     *
     * @return the value of T_J_ORDER.LOAN_ID
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getLoanId() {
        return loanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.LOAN_ID
     *
     * @param loanId the value for T_J_ORDER.LOAN_ID
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setLoanId(String loanId) {
        this.loanId = loanId == null ? null : loanId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.LOAN_PROGRESS
     *
     * @return the value of T_J_ORDER.LOAN_PROGRESS
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public Short getLoanProgress() {
        return loanProgress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.LOAN_PROGRESS
     *
     * @param loanProgress the value for T_J_ORDER.LOAN_PROGRESS
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setLoanProgress(Short loanProgress) {
        this.loanProgress = loanProgress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.LOAN_CONTRACT_NO
     *
     * @return the value of T_J_ORDER.LOAN_CONTRACT_NO
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getLoanContractNo() {
        return loanContractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.LOAN_CONTRACT_NO
     *
     * @param loanContractNo the value for T_J_ORDER.LOAN_CONTRACT_NO
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setLoanContractNo(String loanContractNo) {
        this.loanContractNo = loanContractNo == null ? null : loanContractNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.DUEBILL_NO
     *
     * @return the value of T_J_ORDER.DUEBILL_NO
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getDuebillNo() {
        return duebillNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.DUEBILL_NO
     *
     * @param duebillNo the value for T_J_ORDER.DUEBILL_NO
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setDuebillNo(String duebillNo) {
        this.duebillNo = duebillNo == null ? null : duebillNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.LEND_AMOUNT
     *
     * @return the value of T_J_ORDER.LEND_AMOUNT
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public BigDecimal getLendAmount() {
        return lendAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.LEND_AMOUNT
     *
     * @param lendAmount the value for T_J_ORDER.LEND_AMOUNT
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setLendAmount(BigDecimal lendAmount) {
        this.lendAmount = lendAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.LEND_DATE
     *
     * @return the value of T_J_ORDER.LEND_DATE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getLendDate() {
        return lendDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.LEND_DATE
     *
     * @param lendDate the value for T_J_ORDER.LEND_DATE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setLendDate(String lendDate) {
        this.lendDate = lendDate == null ? null : lendDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.NET_CONTRACT_URL
     *
     * @return the value of T_J_ORDER.NET_CONTRACT_URL
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getNetContractUrl() {
        return netContractUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.NET_CONTRACT_URL
     *
     * @param netContractUrl the value for T_J_ORDER.NET_CONTRACT_URL
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setNetContractUrl(String netContractUrl) {
        this.netContractUrl = netContractUrl == null ? null : netContractUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.REPAY_ACC_NAME
     *
     * @return the value of T_J_ORDER.REPAY_ACC_NAME
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getRepayAccName() {
        return repayAccName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.REPAY_ACC_NAME
     *
     * @param repayAccName the value for T_J_ORDER.REPAY_ACC_NAME
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setRepayAccName(String repayAccName) {
        this.repayAccName = repayAccName == null ? null : repayAccName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.REPAY_ACC_NO
     *
     * @return the value of T_J_ORDER.REPAY_ACC_NO
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getRepayAccNo() {
        return repayAccNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.REPAY_ACC_NO
     *
     * @param repayAccNo the value for T_J_ORDER.REPAY_ACC_NO
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setRepayAccNo(String repayAccNo) {
        this.repayAccNo = repayAccNo == null ? null : repayAccNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.LOAN_RATE
     *
     * @return the value of T_J_ORDER.LOAN_RATE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public BigDecimal getLoanRate() {
        return loanRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.LOAN_RATE
     *
     * @param loanRate the value for T_J_ORDER.LOAN_RATE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setLoanRate(BigDecimal loanRate) {
        this.loanRate = loanRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.OVERDUE_DAY
     *
     * @return the value of T_J_ORDER.OVERDUE_DAY
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public Short getOverdueDay() {
        return overdueDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.OVERDUE_DAY
     *
     * @param overdueDay the value for T_J_ORDER.OVERDUE_DAY
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setOverdueDay(Short overdueDay) {
        this.overdueDay = overdueDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.SERVICE_CHARGE
     *
     * @return the value of T_J_ORDER.SERVICE_CHARGE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public BigDecimal getServiceCharge() {
        return serviceCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.SERVICE_CHARGE
     *
     * @param serviceCharge the value for T_J_ORDER.SERVICE_CHARGE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setServiceCharge(BigDecimal serviceCharge) {
        this.serviceCharge = serviceCharge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.IS_RECEIVED
     *
     * @return the value of T_J_ORDER.IS_RECEIVED
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public Short getIsReceived() {
        return isReceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.IS_RECEIVED
     *
     * @param isReceived the value for T_J_ORDER.IS_RECEIVED
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setIsReceived(Short isReceived) {
        this.isReceived = isReceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.LOAN_LENGTH
     *
     * @return the value of T_J_ORDER.LOAN_LENGTH
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getLoanLength() {
        return loanLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.LOAN_LENGTH
     *
     * @param loanLength the value for T_J_ORDER.LOAN_LENGTH
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setLoanLength(String loanLength) {
        this.loanLength = loanLength == null ? null : loanLength.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.AVAIL_BALANCE
     *
     * @return the value of T_J_ORDER.AVAIL_BALANCE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public BigDecimal getAvailBalance() {
        return availBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.AVAIL_BALANCE
     *
     * @param availBalance the value for T_J_ORDER.AVAIL_BALANCE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setAvailBalance(BigDecimal availBalance) {
        this.availBalance = availBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.YC_MESSAGE
     *
     * @return the value of T_J_ORDER.YC_MESSAGE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getYcMessage() {
        return ycMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.YC_MESSAGE
     *
     * @param ycMessage the value for T_J_ORDER.YC_MESSAGE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setYcMessage(String ycMessage) {
        this.ycMessage = ycMessage == null ? null : ycMessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.DISCOUNT
     *
     * @return the value of T_J_ORDER.DISCOUNT
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.DISCOUNT
     *
     * @param discount the value for T_J_ORDER.DISCOUNT
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.FIXED_REPAY_DATE
     *
     * @return the value of T_J_ORDER.FIXED_REPAY_DATE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public Short getFixedRepayDate() {
        return fixedRepayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.FIXED_REPAY_DATE
     *
     * @param fixedRepayDate the value for T_J_ORDER.FIXED_REPAY_DATE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setFixedRepayDate(Short fixedRepayDate) {
        this.fixedRepayDate = fixedRepayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.ACTUAL_SETTLE_DATE
     *
     * @return the value of T_J_ORDER.ACTUAL_SETTLE_DATE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getActualSettleDate() {
        return actualSettleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.ACTUAL_SETTLE_DATE
     *
     * @param actualSettleDate the value for T_J_ORDER.ACTUAL_SETTLE_DATE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setActualSettleDate(String actualSettleDate) {
        this.actualSettleDate = actualSettleDate == null ? null : actualSettleDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.PAY_ID
     *
     * @return the value of T_J_ORDER.PAY_ID
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.PAY_ID
     *
     * @param payId the value for T_J_ORDER.PAY_ID
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setPayId(String payId) {
        this.payId = payId == null ? null : payId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.REAL_ORDER_ID
     *
     * @return the value of T_J_ORDER.REAL_ORDER_ID
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getRealOrderId() {
        return realOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.REAL_ORDER_ID
     *
     * @param realOrderId the value for T_J_ORDER.REAL_ORDER_ID
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setRealOrderId(String realOrderId) {
        this.realOrderId = realOrderId == null ? null : realOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.REAL_ORDER_AMOUNT
     *
     * @return the value of T_J_ORDER.REAL_ORDER_AMOUNT
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public BigDecimal getRealOrderAmount() {
        return realOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.REAL_ORDER_AMOUNT
     *
     * @param realOrderAmount the value for T_J_ORDER.REAL_ORDER_AMOUNT
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setRealOrderAmount(BigDecimal realOrderAmount) {
        this.realOrderAmount = realOrderAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.PX_NO
     *
     * @return the value of T_J_ORDER.PX_NO
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getPxNo() {
        return pxNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.PX_NO
     *
     * @param pxNo the value for T_J_ORDER.PX_NO
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setPxNo(String pxNo) {
        this.pxNo = pxNo == null ? null : pxNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_ORDER.LOAN_TYPE
     *
     * @return the value of T_J_ORDER.LOAN_TYPE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public String getLoanType() {
        return loanType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_ORDER.LOAN_TYPE
     *
     * @param loanType the value for T_J_ORDER.LOAN_TYPE
     *
     * @mbggenerated Thu Oct 12 09:47:05 CST 2017
     */
    public void setLoanType(String loanType) {
        this.loanType = loanType == null ? null : loanType.trim();
    }
}