package com.ule.uhj.app.zgd.model;

public class SaleActInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_SALE_ACT.CODE
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_SALE_ACT.NAME
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_SALE_ACT.DESCRIPTION
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_SALE_ACT.FINISH_DESC
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    private String finishDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_SALE_ACT.BEGIN_DATE
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    private String beginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_SALE_ACT.END_DATE
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_SALE_ACT.VALID_FLAG
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    private String validFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_SALE_ACT.STATUS
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_SALE_ACT.CREATE_TIME
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_SALE_ACT.CREATE_USER
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_SALE_ACT.UPDATE_TIME
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_SALE_ACT.UPDATE_USER
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_SALE_ACT.CODE
     *
     * @return the value of T_J_SALE_ACT.CODE
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_SALE_ACT.CODE
     *
     * @param code the value for T_J_SALE_ACT.CODE
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_SALE_ACT.NAME
     *
     * @return the value of T_J_SALE_ACT.NAME
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_SALE_ACT.NAME
     *
     * @param name the value for T_J_SALE_ACT.NAME
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_SALE_ACT.DESCRIPTION
     *
     * @return the value of T_J_SALE_ACT.DESCRIPTION
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_SALE_ACT.DESCRIPTION
     *
     * @param description the value for T_J_SALE_ACT.DESCRIPTION
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_SALE_ACT.FINISH_DESC
     *
     * @return the value of T_J_SALE_ACT.FINISH_DESC
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public String getFinishDesc() {
        return finishDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_SALE_ACT.FINISH_DESC
     *
     * @param finishDesc the value for T_J_SALE_ACT.FINISH_DESC
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public void setFinishDesc(String finishDesc) {
        this.finishDesc = finishDesc == null ? null : finishDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_SALE_ACT.BEGIN_DATE
     *
     * @return the value of T_J_SALE_ACT.BEGIN_DATE
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public String getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_SALE_ACT.BEGIN_DATE
     *
     * @param beginDate the value for T_J_SALE_ACT.BEGIN_DATE
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public void setBeginDate(String beginDate) {
        this.beginDate = beginDate == null ? null : beginDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_SALE_ACT.END_DATE
     *
     * @return the value of T_J_SALE_ACT.END_DATE
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_SALE_ACT.END_DATE
     *
     * @param endDate the value for T_J_SALE_ACT.END_DATE
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_SALE_ACT.VALID_FLAG
     *
     * @return the value of T_J_SALE_ACT.VALID_FLAG
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public String getValidFlag() {
        return validFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_SALE_ACT.VALID_FLAG
     *
     * @param validFlag the value for T_J_SALE_ACT.VALID_FLAG
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public void setValidFlag(String validFlag) {
        this.validFlag = validFlag == null ? null : validFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_SALE_ACT.STATUS
     *
     * @return the value of T_J_SALE_ACT.STATUS
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_SALE_ACT.STATUS
     *
     * @param status the value for T_J_SALE_ACT.STATUS
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_SALE_ACT.CREATE_TIME
     *
     * @return the value of T_J_SALE_ACT.CREATE_TIME
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_SALE_ACT.CREATE_TIME
     *
     * @param createTime the value for T_J_SALE_ACT.CREATE_TIME
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_SALE_ACT.CREATE_USER
     *
     * @return the value of T_J_SALE_ACT.CREATE_USER
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_SALE_ACT.CREATE_USER
     *
     * @param createUser the value for T_J_SALE_ACT.CREATE_USER
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_SALE_ACT.UPDATE_TIME
     *
     * @return the value of T_J_SALE_ACT.UPDATE_TIME
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_SALE_ACT.UPDATE_TIME
     *
     * @param updateTime the value for T_J_SALE_ACT.UPDATE_TIME
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_SALE_ACT.UPDATE_USER
     *
     * @return the value of T_J_SALE_ACT.UPDATE_USER
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_SALE_ACT.UPDATE_USER
     *
     * @param updateUser the value for T_J_SALE_ACT.UPDATE_USER
     *
     * @mbggenerated Thu May 10 15:20:08 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }
}