package com.ule.uhj.sldProxy.model;

public class InterfaceAccessInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_INTERFACE_ACCESS_INFO.ID
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_INTERFACE_ACCESS_INFO.USER_ONLY_ID
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    private String userOnlyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_INTERFACE_ACCESS_INFO.APP_ID
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_INTERFACE_ACCESS_INFO.TYPE
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_INTERFACE_ACCESS_INFO.INTERFACE_TYPE
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    private String interfaceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_INTERFACE_ACCESS_INFO.DATA_RELATION
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    private String dataRelation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_INTERFACE_ACCESS_INFO.STATUS
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_INTERFACE_ACCESS_INFO.REST_ACCESSS_COUNT
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    private Short restAccesssCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_INTERFACE_ACCESS_INFO.EXCEPTION_LOG
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    private String exceptionLog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_INTERFACE_ACCESS_INFO.CREATE_TIME
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_INTERFACE_ACCESS_INFO.UPDATE_TIME
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_INTERFACE_ACCESS_INFO.REMARK
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_INTERFACE_ACCESS_INFO.ID
     *
     * @return the value of T_J_INTERFACE_ACCESS_INFO.ID
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_INTERFACE_ACCESS_INFO.ID
     *
     * @param id the value for T_J_INTERFACE_ACCESS_INFO.ID
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_INTERFACE_ACCESS_INFO.USER_ONLY_ID
     *
     * @return the value of T_J_INTERFACE_ACCESS_INFO.USER_ONLY_ID
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public String getUserOnlyId() {
        return userOnlyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_INTERFACE_ACCESS_INFO.USER_ONLY_ID
     *
     * @param userOnlyId the value for T_J_INTERFACE_ACCESS_INFO.USER_ONLY_ID
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public void setUserOnlyId(String userOnlyId) {
        this.userOnlyId = userOnlyId == null ? null : userOnlyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_INTERFACE_ACCESS_INFO.APP_ID
     *
     * @return the value of T_J_INTERFACE_ACCESS_INFO.APP_ID
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_INTERFACE_ACCESS_INFO.APP_ID
     *
     * @param appId the value for T_J_INTERFACE_ACCESS_INFO.APP_ID
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_INTERFACE_ACCESS_INFO.TYPE
     *
     * @return the value of T_J_INTERFACE_ACCESS_INFO.TYPE
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_INTERFACE_ACCESS_INFO.TYPE
     *
     * @param type the value for T_J_INTERFACE_ACCESS_INFO.TYPE
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_INTERFACE_ACCESS_INFO.INTERFACE_TYPE
     *
     * @return the value of T_J_INTERFACE_ACCESS_INFO.INTERFACE_TYPE
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public String getInterfaceType() {
        return interfaceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_INTERFACE_ACCESS_INFO.INTERFACE_TYPE
     *
     * @param interfaceType the value for T_J_INTERFACE_ACCESS_INFO.INTERFACE_TYPE
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public void setInterfaceType(String interfaceType) {
        this.interfaceType = interfaceType == null ? null : interfaceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_INTERFACE_ACCESS_INFO.DATA_RELATION
     *
     * @return the value of T_J_INTERFACE_ACCESS_INFO.DATA_RELATION
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public String getDataRelation() {
        return dataRelation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_INTERFACE_ACCESS_INFO.DATA_RELATION
     *
     * @param dataRelation the value for T_J_INTERFACE_ACCESS_INFO.DATA_RELATION
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public void setDataRelation(String dataRelation) {
        this.dataRelation = dataRelation == null ? null : dataRelation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_INTERFACE_ACCESS_INFO.STATUS
     *
     * @return the value of T_J_INTERFACE_ACCESS_INFO.STATUS
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_INTERFACE_ACCESS_INFO.STATUS
     *
     * @param status the value for T_J_INTERFACE_ACCESS_INFO.STATUS
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_INTERFACE_ACCESS_INFO.REST_ACCESSS_COUNT
     *
     * @return the value of T_J_INTERFACE_ACCESS_INFO.REST_ACCESSS_COUNT
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public Short getRestAccesssCount() {
        return restAccesssCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_INTERFACE_ACCESS_INFO.REST_ACCESSS_COUNT
     *
     * @param restAccesssCount the value for T_J_INTERFACE_ACCESS_INFO.REST_ACCESSS_COUNT
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public void setRestAccesssCount(Short restAccesssCount) {
        this.restAccesssCount = restAccesssCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_INTERFACE_ACCESS_INFO.EXCEPTION_LOG
     *
     * @return the value of T_J_INTERFACE_ACCESS_INFO.EXCEPTION_LOG
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public String getExceptionLog() {
        return exceptionLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_INTERFACE_ACCESS_INFO.EXCEPTION_LOG
     *
     * @param exceptionLog the value for T_J_INTERFACE_ACCESS_INFO.EXCEPTION_LOG
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public void setExceptionLog(String exceptionLog) {
        this.exceptionLog = exceptionLog == null ? null : exceptionLog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_INTERFACE_ACCESS_INFO.CREATE_TIME
     *
     * @return the value of T_J_INTERFACE_ACCESS_INFO.CREATE_TIME
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_INTERFACE_ACCESS_INFO.CREATE_TIME
     *
     * @param createTime the value for T_J_INTERFACE_ACCESS_INFO.CREATE_TIME
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_INTERFACE_ACCESS_INFO.UPDATE_TIME
     *
     * @return the value of T_J_INTERFACE_ACCESS_INFO.UPDATE_TIME
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_INTERFACE_ACCESS_INFO.UPDATE_TIME
     *
     * @param updateTime the value for T_J_INTERFACE_ACCESS_INFO.UPDATE_TIME
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_INTERFACE_ACCESS_INFO.REMARK
     *
     * @return the value of T_J_INTERFACE_ACCESS_INFO.REMARK
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_INTERFACE_ACCESS_INFO.REMARK
     *
     * @param remark the value for T_J_INTERFACE_ACCESS_INFO.REMARK
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}