package com.ule.uhj.app.zgd.dao;

import com.ule.uhj.app.zgd.model.RepayPlan;
import com.ule.uhj.app.zgd.model.RepayPlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RepayPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_REPAY_PLAN
     *
     * @mbggenerated Wed Jun 27 10:35:41 CST 2018
     */
    int countByExample(RepayPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_REPAY_PLAN
     *
     * @mbggenerated Wed Jun 27 10:35:41 CST 2018
     */
    int deleteByExample(RepayPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_REPAY_PLAN
     *
     * @mbggenerated Wed Jun 27 10:35:41 CST 2018
     */
    int deleteByPrimaryKey(String planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_REPAY_PLAN
     *
     * @mbggenerated Wed Jun 27 10:35:41 CST 2018
     */
    int insert(RepayPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_REPAY_PLAN
     *
     * @mbggenerated Wed Jun 27 10:35:41 CST 2018
     */
    int insertSelective(RepayPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_REPAY_PLAN
     *
     * @mbggenerated Wed Jun 27 10:35:41 CST 2018
     */
    List<RepayPlan> selectByExample(RepayPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_REPAY_PLAN
     *
     * @mbggenerated Wed Jun 27 10:35:41 CST 2018
     */
    RepayPlan selectByPrimaryKey(String planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_REPAY_PLAN
     *
     * @mbggenerated Wed Jun 27 10:35:41 CST 2018
     */
    int updateByExampleSelective(@Param("record") RepayPlan record, @Param("example") RepayPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_REPAY_PLAN
     *
     * @mbggenerated Wed Jun 27 10:35:41 CST 2018
     */
    int updateByExample(@Param("record") RepayPlan record, @Param("example") RepayPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_REPAY_PLAN
     *
     * @mbggenerated Wed Jun 27 10:35:41 CST 2018
     */
    int updateByPrimaryKeySelective(RepayPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_REPAY_PLAN
     *
     * @mbggenerated Wed Jun 27 10:35:41 CST 2018
     */
    int updateByPrimaryKey(RepayPlan record);
}