package com.ule.uhj.sldProxy.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ule.uhj.sldProxy.model.InterfaceAccessInfo;
import com.ule.uhj.sldProxy.model.InterfaceAccessInfoExample;
import com.ule.uhj.sldProxy.model.InterfaceAccessInfoWithBLOBs;

public interface InterfaceAccessInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_ACCESS_INFO
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    int countByExample(InterfaceAccessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_ACCESS_INFO
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    int deleteByExample(InterfaceAccessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_ACCESS_INFO
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    int insert(InterfaceAccessInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_ACCESS_INFO
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    int insertSelective(InterfaceAccessInfoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_ACCESS_INFO
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    List<InterfaceAccessInfoWithBLOBs> selectByExampleWithBLOBs(InterfaceAccessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_ACCESS_INFO
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    List<InterfaceAccessInfo> selectByExample(InterfaceAccessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_ACCESS_INFO
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    int updateByExampleSelective(@Param("record") InterfaceAccessInfoWithBLOBs record, @Param("example") InterfaceAccessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_ACCESS_INFO
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") InterfaceAccessInfoWithBLOBs record, @Param("example") InterfaceAccessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_INTERFACE_ACCESS_INFO
     *
     * @mbggenerated Wed May 10 19:07:57 CST 2017
     */
    int updateByExample(@Param("record") InterfaceAccessInfo record, @Param("example") InterfaceAccessInfoExample example);
}