package com.ule.oracle.model;

import java.math.BigDecimal;

public class Constant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CONSTANT.ID
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CONSTANT.TYPE_CODE
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CONSTANT.TYPE_NAME
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CONSTANT.ELEMENT_KEY
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    private String elementKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CONSTANT.ELEMENT_VALUE
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    private String elementValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CONSTANT.CREATE_TIME
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CONSTANT.CREATOR
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CONSTANT.UPDATE_TIME
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CONSTANT.UPDATOR
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    private String updator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CONSTANT.REMARK
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CONSTANT.STATUS
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    private Short status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CONSTANT.ID
     *
     * @return the value of T_J_CONSTANT.ID
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CONSTANT.ID
     *
     * @param id the value for T_J_CONSTANT.ID
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CONSTANT.TYPE_CODE
     *
     * @return the value of T_J_CONSTANT.TYPE_CODE
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CONSTANT.TYPE_CODE
     *
     * @param typeCode the value for T_J_CONSTANT.TYPE_CODE
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CONSTANT.TYPE_NAME
     *
     * @return the value of T_J_CONSTANT.TYPE_NAME
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CONSTANT.TYPE_NAME
     *
     * @param typeName the value for T_J_CONSTANT.TYPE_NAME
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CONSTANT.ELEMENT_KEY
     *
     * @return the value of T_J_CONSTANT.ELEMENT_KEY
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public String getElementKey() {
        return elementKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CONSTANT.ELEMENT_KEY
     *
     * @param elementKey the value for T_J_CONSTANT.ELEMENT_KEY
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public void setElementKey(String elementKey) {
        this.elementKey = elementKey == null ? null : elementKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CONSTANT.ELEMENT_VALUE
     *
     * @return the value of T_J_CONSTANT.ELEMENT_VALUE
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public String getElementValue() {
        return elementValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CONSTANT.ELEMENT_VALUE
     *
     * @param elementValue the value for T_J_CONSTANT.ELEMENT_VALUE
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public void setElementValue(String elementValue) {
        this.elementValue = elementValue == null ? null : elementValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CONSTANT.CREATE_TIME
     *
     * @return the value of T_J_CONSTANT.CREATE_TIME
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CONSTANT.CREATE_TIME
     *
     * @param createTime the value for T_J_CONSTANT.CREATE_TIME
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CONSTANT.CREATOR
     *
     * @return the value of T_J_CONSTANT.CREATOR
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CONSTANT.CREATOR
     *
     * @param creator the value for T_J_CONSTANT.CREATOR
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CONSTANT.UPDATE_TIME
     *
     * @return the value of T_J_CONSTANT.UPDATE_TIME
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CONSTANT.UPDATE_TIME
     *
     * @param updateTime the value for T_J_CONSTANT.UPDATE_TIME
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CONSTANT.UPDATOR
     *
     * @return the value of T_J_CONSTANT.UPDATOR
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public String getUpdator() {
        return updator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CONSTANT.UPDATOR
     *
     * @param updator the value for T_J_CONSTANT.UPDATOR
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public void setUpdator(String updator) {
        this.updator = updator == null ? null : updator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CONSTANT.REMARK
     *
     * @return the value of T_J_CONSTANT.REMARK
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CONSTANT.REMARK
     *
     * @param remark the value for T_J_CONSTANT.REMARK
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CONSTANT.STATUS
     *
     * @return the value of T_J_CONSTANT.STATUS
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CONSTANT.STATUS
     *
     * @param status the value for T_J_CONSTANT.STATUS
     *
     * @mbggenerated Mon Mar 18 16:09:18 CST 2019
     */
    public void setStatus(Short status) {
        this.status = status;
    }
}