package com.ule.oracle.model;

import java.util.Date;

public class InterfaceBlock {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_INTERFACE_BLOCK.ID
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_INTERFACE_BLOCK.USER_ONLY_ID
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    private String userOnlyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_INTERFACE_BLOCK.INTERFACE_CODE
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    private String interfaceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_INTERFACE_BLOCK.INTERFACE_TYPE
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    private String interfaceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_INTERFACE_BLOCK.STATUS
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_INTERFACE_BLOCK.ROW_CREATE_TIME
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    private Date rowCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_INTERFACE_BLOCK.ROW_LASTUPDATE_TIME
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    private Date rowLastupdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_INTERFACE_BLOCK.REMARK
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_INTERFACE_BLOCK.BLOCK_TEXT
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    private byte[] blockText;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_INTERFACE_BLOCK.ID
     *
     * @return the value of T_J_INTERFACE_BLOCK.ID
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_INTERFACE_BLOCK.ID
     *
     * @param id the value for T_J_INTERFACE_BLOCK.ID
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_INTERFACE_BLOCK.USER_ONLY_ID
     *
     * @return the value of T_J_INTERFACE_BLOCK.USER_ONLY_ID
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    public String getUserOnlyId() {
        return userOnlyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_INTERFACE_BLOCK.USER_ONLY_ID
     *
     * @param userOnlyId the value for T_J_INTERFACE_BLOCK.USER_ONLY_ID
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    public void setUserOnlyId(String userOnlyId) {
        this.userOnlyId = userOnlyId == null ? null : userOnlyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_INTERFACE_BLOCK.INTERFACE_CODE
     *
     * @return the value of T_J_INTERFACE_BLOCK.INTERFACE_CODE
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    public String getInterfaceCode() {
        return interfaceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_INTERFACE_BLOCK.INTERFACE_CODE
     *
     * @param interfaceCode the value for T_J_INTERFACE_BLOCK.INTERFACE_CODE
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    public void setInterfaceCode(String interfaceCode) {
        this.interfaceCode = interfaceCode == null ? null : interfaceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_INTERFACE_BLOCK.INTERFACE_TYPE
     *
     * @return the value of T_J_INTERFACE_BLOCK.INTERFACE_TYPE
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    public String getInterfaceType() {
        return interfaceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_INTERFACE_BLOCK.INTERFACE_TYPE
     *
     * @param interfaceType the value for T_J_INTERFACE_BLOCK.INTERFACE_TYPE
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    public void setInterfaceType(String interfaceType) {
        this.interfaceType = interfaceType == null ? null : interfaceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_INTERFACE_BLOCK.STATUS
     *
     * @return the value of T_J_INTERFACE_BLOCK.STATUS
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_INTERFACE_BLOCK.STATUS
     *
     * @param status the value for T_J_INTERFACE_BLOCK.STATUS
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_INTERFACE_BLOCK.ROW_CREATE_TIME
     *
     * @return the value of T_J_INTERFACE_BLOCK.ROW_CREATE_TIME
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    public Date getRowCreateTime() {
        return rowCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_INTERFACE_BLOCK.ROW_CREATE_TIME
     *
     * @param rowCreateTime the value for T_J_INTERFACE_BLOCK.ROW_CREATE_TIME
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    public void setRowCreateTime(Date rowCreateTime) {
        this.rowCreateTime = rowCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_INTERFACE_BLOCK.ROW_LASTUPDATE_TIME
     *
     * @return the value of T_J_INTERFACE_BLOCK.ROW_LASTUPDATE_TIME
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    public Date getRowLastupdateTime() {
        return rowLastupdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_INTERFACE_BLOCK.ROW_LASTUPDATE_TIME
     *
     * @param rowLastupdateTime the value for T_J_INTERFACE_BLOCK.ROW_LASTUPDATE_TIME
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    public void setRowLastupdateTime(Date rowLastupdateTime) {
        this.rowLastupdateTime = rowLastupdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_INTERFACE_BLOCK.REMARK
     *
     * @return the value of T_J_INTERFACE_BLOCK.REMARK
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_INTERFACE_BLOCK.REMARK
     *
     * @param remark the value for T_J_INTERFACE_BLOCK.REMARK
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_INTERFACE_BLOCK.BLOCK_TEXT
     *
     * @return the value of T_J_INTERFACE_BLOCK.BLOCK_TEXT
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    public byte[] getBlockText() {
        return blockText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_INTERFACE_BLOCK.BLOCK_TEXT
     *
     * @param blockText the value for T_J_INTERFACE_BLOCK.BLOCK_TEXT
     *
     * @mbggenerated Mon Jun 29 17:19:17 CST 2020
     */
    public void setBlockText(byte[] blockText) {
        this.blockText = blockText;
    }
}