package com.ule.uhj.app.zgd.dao;

import com.ule.uhj.app.zgd.model.AutoRepaySettingInfo;
import com.ule.uhj.app.zgd.model.AutoRepaySettingInfoExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AutoRepaySettingInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_SETTING
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    int countByExample(AutoRepaySettingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_SETTING
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    int deleteByExample(AutoRepaySettingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_SETTING
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_SETTING
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    int insert(AutoRepaySettingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_SETTING
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    int insertSelective(AutoRepaySettingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_SETTING
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    List<AutoRepaySettingInfo> selectByExample(AutoRepaySettingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_SETTING
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    AutoRepaySettingInfo selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_SETTING
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") AutoRepaySettingInfo record, @Param("example") AutoRepaySettingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_SETTING
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    int updateByExample(@Param("record") AutoRepaySettingInfo record, @Param("example") AutoRepaySettingInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_SETTING
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    int updateByPrimaryKeySelective(AutoRepaySettingInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_AUTO_REPAY_SETTING
     *
     * @mbggenerated Thu Apr 12 15:30:27 CST 2018
     */
    int updateByPrimaryKey(AutoRepaySettingInfo record);
    
    /**
     * 根据userOnlyId查询此人是否已经设置了自动还款
     * 返回值大于0表示已设置
     * @param userOnlyId
     * @return
     */
    int selectSetting(String userOnlyId);
}