package com.ule.uhj.app.zgd.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.ule.uhj.app.zgd.model.CountryAddress;
import com.ule.uhj.app.zgd.model.CountryAddressExample;

public interface CountryAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_COUNTRY_ADDRESS
     *
     * @mbggenerated Mon May 22 17:52:30 CST 2017
     */
    int countByExample(CountryAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_COUNTRY_ADDRESS
     *
     * @mbggenerated Mon May 22 17:52:30 CST 2017
     */
    int deleteByExample(CountryAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_COUNTRY_ADDRESS
     *
     * @mbggenerated Mon May 22 17:52:30 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_COUNTRY_ADDRESS
     *
     * @mbggenerated Mon May 22 17:52:30 CST 2017
     */
    int insert(CountryAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_COUNTRY_ADDRESS
     *
     * @mbggenerated Mon May 22 17:52:30 CST 2017
     */
    int insertSelective(CountryAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_COUNTRY_ADDRESS
     *
     * @mbggenerated Mon May 22 17:52:30 CST 2017
     */
    List<CountryAddress> selectByExample(CountryAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_COUNTRY_ADDRESS
     *
     * @mbggenerated Mon May 22 17:52:30 CST 2017
     */
    CountryAddress selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_COUNTRY_ADDRESS
     *
     * @mbggenerated Mon May 22 17:52:30 CST 2017
     */
    int updateByExampleSelective(@Param("record") CountryAddress record, @Param("example") CountryAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_COUNTRY_ADDRESS
     *
     * @mbggenerated Mon May 22 17:52:30 CST 2017
     */
    int updateByExample(@Param("record") CountryAddress record, @Param("example") CountryAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_COUNTRY_ADDRESS
     *
     * @mbggenerated Mon May 22 17:52:30 CST 2017
     */
    int updateByPrimaryKeySelective(CountryAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_COUNTRY_ADDRESS
     *
     * @mbggenerated Mon May 22 17:52:30 CST 2017
     */
    int updateByPrimaryKey(CountryAddress record);
    
    List<CountryAddress> selectBySubordinateName(Map<String,Object> map);
    
    List<CountryAddress> selectProvinceName();
    
    List<CountryAddress> selectCityName();
    
    List<CountryAddress> selectCountyName();
    
    List<CountryAddress> selectCityByProvince(String code);
    
    List<CountryAddress> selectCountyByProvince(String code);
}