package com.ule.uhj.app.zgd.dao;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ule.uhj.app.zgd.model.CreditPostmember;
import com.ule.uhj.app.zgd.model.CreditPostmemberExample;

public interface CreditPostmemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_POSTMEMBER
     *
     * @mbggenerated Wed Oct 11 10:31:44 CST 2017
     */
    int countByExample(CreditPostmemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_POSTMEMBER
     *
     * @mbggenerated Wed Oct 11 10:31:44 CST 2017
     */
    int deleteByExample(CreditPostmemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_POSTMEMBER
     *
     * @mbggenerated Wed Oct 11 10:31:44 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_POSTMEMBER
     *
     * @mbggenerated Wed Oct 11 10:31:44 CST 2017
     */
    int insert(CreditPostmember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_POSTMEMBER
     *
     * @mbggenerated Wed Oct 11 10:31:44 CST 2017
     */
    int insertSelective(CreditPostmember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_POSTMEMBER
     *
     * @mbggenerated Wed Oct 11 10:31:44 CST 2017
     */
    List<CreditPostmember> selectByExample(CreditPostmemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_POSTMEMBER
     *
     * @mbggenerated Wed Oct 11 10:31:44 CST 2017
     */
    CreditPostmember selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_POSTMEMBER
     *
     * @mbggenerated Wed Oct 11 10:31:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") CreditPostmember record, @Param("example") CreditPostmemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_POSTMEMBER
     *
     * @mbggenerated Wed Oct 11 10:31:44 CST 2017
     */
    int updateByExample(@Param("record") CreditPostmember record, @Param("example") CreditPostmemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_POSTMEMBER
     *
     * @mbggenerated Wed Oct 11 10:31:44 CST 2017
     */
    int updateByPrimaryKeySelective(CreditPostmember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_POSTMEMBER
     *
     * @mbggenerated Wed Oct 11 10:31:44 CST 2017
     */
    int updateByPrimaryKey(CreditPostmember record);
}