package com.ule.uhj.app.zgd.dao;

import java.math.BigDecimal;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ule.uhj.app.zgd.model.CreditAudit;
import com.ule.uhj.app.zgd.model.CreditAuditExample;

public interface CreditAuditMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_AUDIT
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    int countByExample(CreditAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_AUDIT
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    int deleteByExample(CreditAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_AUDIT
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_AUDIT
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    int insert(CreditAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_AUDIT
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    int insertSelective(CreditAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_AUDIT
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    List<CreditAudit> selectByExample(CreditAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_AUDIT
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    CreditAudit selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_AUDIT
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") CreditAudit record, @Param("example") CreditAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_AUDIT
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    int updateByExample(@Param("record") CreditAudit record, @Param("example") CreditAuditExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_AUDIT
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    int updateByPrimaryKeySelective(CreditAudit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_CREDIT_AUDIT
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    int updateByPrimaryKey(CreditAudit record);
    
    List<CreditAudit> selectByParam(CreditAudit creditAudit);
}