package com.ule.uhj.app.zgd.dao;

import com.ule.uhj.app.zgd.model.ForecastScope;
import com.ule.uhj.app.zgd.model.ForecastScopeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ForecastScopeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    int countByExample(ForecastScopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    int deleteByExample(ForecastScopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    int insert(ForecastScope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    int insertSelective(ForecastScope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    List<ForecastScope> selectByExample(ForecastScopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    ForecastScope selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") ForecastScope record, @Param("example") ForecastScopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    int updateByExample(@Param("record") ForecastScope record, @Param("example") ForecastScopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    int updateByPrimaryKeySelective(ForecastScope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_FORECAST_SCOPE
     *
     * @mbggenerated Thu Jun 21 14:35:47 CST 2018
     */
    int updateByPrimaryKey(ForecastScope record);
    
    List<String>selectByBusinessScope(String scope);
}