package com.ule.uhj.app.zgd.dao;

import com.ule.uhj.app.zgd.model.Notice;
import com.ule.uhj.app.zgd.model.NoticeExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_NOTICE
     *
     * @mbggenerated Thu Jun 28 18:26:39 CST 2018
     */
    int countByExample(NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_NOTICE
     *
     * @mbggenerated Thu Jun 28 18:26:39 CST 2018
     */
    int deleteByExample(NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_NOTICE
     *
     * @mbggenerated Thu Jun 28 18:26:39 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_NOTICE
     *
     * @mbggenerated Thu Jun 28 18:26:39 CST 2018
     */
    int insert(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_NOTICE
     *
     * @mbggenerated Thu Jun 28 18:26:39 CST 2018
     */
    int insertSelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_NOTICE
     *
     * @mbggenerated Thu Jun 28 18:26:39 CST 2018
     */
    List<Notice> selectByExample(NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_NOTICE
     *
     * @mbggenerated Thu Jun 28 18:26:39 CST 2018
     */
    Notice selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_NOTICE
     *
     * @mbggenerated Thu Jun 28 18:26:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") Notice record, @Param("example") NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_NOTICE
     *
     * @mbggenerated Thu Jun 28 18:26:39 CST 2018
     */
    int updateByExample(@Param("record") Notice record, @Param("example") NoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_NOTICE
     *
     * @mbggenerated Thu Jun 28 18:26:39 CST 2018
     */
    int updateByPrimaryKeySelective(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_NOTICE
     *
     * @mbggenerated Thu Jun 28 18:26:39 CST 2018
     */
    int updateByPrimaryKey(Notice record);
}