package com.ule.uhj.app.zgd.dao;

import com.ule.uhj.app.zgd.model.RuleExeSet;
import com.ule.uhj.app.zgd.model.RuleExeSetExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RuleExeSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_RULE_EXE_SET
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    int countByExample(RuleExeSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_RULE_EXE_SET
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    int deleteByExample(RuleExeSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_RULE_EXE_SET
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_RULE_EXE_SET
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    int insert(RuleExeSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_RULE_EXE_SET
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    int insertSelective(RuleExeSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_RULE_EXE_SET
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    List<RuleExeSet> selectByExample(RuleExeSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_RULE_EXE_SET
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    RuleExeSet selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_RULE_EXE_SET
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    int updateByExampleSelective(@Param("record") RuleExeSet record, @Param("example") RuleExeSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_RULE_EXE_SET
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    int updateByExample(@Param("record") RuleExeSet record, @Param("example") RuleExeSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_RULE_EXE_SET
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    int updateByPrimaryKeySelective(RuleExeSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_RULE_EXE_SET
     *
     * @mbggenerated Tue Mar 27 10:15:17 CST 2018
     */
    int updateByPrimaryKey(RuleExeSet record);
}