package com.ule.uhj.app.zgd.dao;

import com.ule.uhj.app.zgd.model.SaleActTicketType;
import com.ule.uhj.app.zgd.model.SaleActTicketTypeExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaleActTicketTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_TICKET_TYPE
     *
     * @mbggenerated Mon May 28 11:10:29 CST 2018
     */
    int countByExample(SaleActTicketTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_TICKET_TYPE
     *
     * @mbggenerated Mon May 28 11:10:29 CST 2018
     */
    int deleteByExample(SaleActTicketTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_TICKET_TYPE
     *
     * @mbggenerated Mon May 28 11:10:29 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_TICKET_TYPE
     *
     * @mbggenerated Mon May 28 11:10:29 CST 2018
     */
    int insert(SaleActTicketType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_TICKET_TYPE
     *
     * @mbggenerated Mon May 28 11:10:29 CST 2018
     */
    int insertSelective(SaleActTicketType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_TICKET_TYPE
     *
     * @mbggenerated Mon May 28 11:10:29 CST 2018
     */
    List<SaleActTicketType> selectByExample(SaleActTicketTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_TICKET_TYPE
     *
     * @mbggenerated Mon May 28 11:10:29 CST 2018
     */
    SaleActTicketType selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_TICKET_TYPE
     *
     * @mbggenerated Mon May 28 11:10:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") SaleActTicketType record, @Param("example") SaleActTicketTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_TICKET_TYPE
     *
     * @mbggenerated Mon May 28 11:10:29 CST 2018
     */
    int updateByExample(@Param("record") SaleActTicketType record, @Param("example") SaleActTicketTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_TICKET_TYPE
     *
     * @mbggenerated Mon May 28 11:10:29 CST 2018
     */
    int updateByPrimaryKeySelective(SaleActTicketType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_ACT_TICKET_TYPE
     *
     * @mbggenerated Mon May 28 11:10:29 CST 2018
     */
    int updateByPrimaryKey(SaleActTicketType record);
}