package com.ule.uhj.app.zgd.dao;

import com.ule.uhj.app.zgd.model.SaleTicketOrder;
import com.ule.uhj.app.zgd.model.SaleTicketOrderExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaleTicketOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_TICKET_ORDER
     *
     * @mbggenerated Mon May 14 09:47:59 CST 2018
     */
    int countByExample(SaleTicketOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_TICKET_ORDER
     *
     * @mbggenerated Mon May 14 09:47:59 CST 2018
     */
    int deleteByExample(SaleTicketOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_TICKET_ORDER
     *
     * @mbggenerated Mon May 14 09:47:59 CST 2018
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_TICKET_ORDER
     *
     * @mbggenerated Mon May 14 09:47:59 CST 2018
     */
    int insert(SaleTicketOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_TICKET_ORDER
     *
     * @mbggenerated Mon May 14 09:47:59 CST 2018
     */
    int insertSelective(SaleTicketOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_TICKET_ORDER
     *
     * @mbggenerated Mon May 14 09:47:59 CST 2018
     */
    List<SaleTicketOrder> selectByExample(SaleTicketOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_TICKET_ORDER
     *
     * @mbggenerated Mon May 14 09:47:59 CST 2018
     */
    SaleTicketOrder selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_TICKET_ORDER
     *
     * @mbggenerated Mon May 14 09:47:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") SaleTicketOrder record, @Param("example") SaleTicketOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_TICKET_ORDER
     *
     * @mbggenerated Mon May 14 09:47:59 CST 2018
     */
    int updateByExample(@Param("record") SaleTicketOrder record, @Param("example") SaleTicketOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_TICKET_ORDER
     *
     * @mbggenerated Mon May 14 09:47:59 CST 2018
     */
    int updateByPrimaryKeySelective(SaleTicketOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_J_SALE_TICKET_ORDER
     *
     * @mbggenerated Mon May 14 09:47:59 CST 2018
     */
    int updateByPrimaryKey(SaleTicketOrder record);
}