package com.ule.uhj.app.zgd.model;

import java.math.BigDecimal;

public class CustomerInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_INFO.ID
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_INFO.USER_ONLY_ID
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    private String userOnlyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_INFO.CUSTOMER_NAME
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_INFO.MARITAL_STATUS
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    private BigDecimal maritalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_INFO.COUNTRY
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_INFO.NATIONALITY
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_INFO.HEALTH
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    private String health;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_INFO.EDUCATION
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_INFO.NATIVE_LIVE_TIME
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    private Short nativeLiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_INFO.TRADE_WORK_YEARS
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    private Short tradeWorkYears;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_INFO.CREATE_TIME
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_INFO.CREATE_USER
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_INFO.UPDATE_TIME
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_INFO.UPDATE_USER
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_INFO.ORG_CODE
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_INFO.CHANNEL_NAME
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_INFO.CHANNEL_CODE
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    private String channelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_J_CUSTOMER_INFO.SALES_CHANNEL
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    private String salesChannel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_INFO.ID
     *
     * @return the value of T_J_CUSTOMER_INFO.ID
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_INFO.ID
     *
     * @param id the value for T_J_CUSTOMER_INFO.ID
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_INFO.USER_ONLY_ID
     *
     * @return the value of T_J_CUSTOMER_INFO.USER_ONLY_ID
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public String getUserOnlyId() {
        return userOnlyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_INFO.USER_ONLY_ID
     *
     * @param userOnlyId the value for T_J_CUSTOMER_INFO.USER_ONLY_ID
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public void setUserOnlyId(String userOnlyId) {
        this.userOnlyId = userOnlyId == null ? null : userOnlyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_INFO.CUSTOMER_NAME
     *
     * @return the value of T_J_CUSTOMER_INFO.CUSTOMER_NAME
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_INFO.CUSTOMER_NAME
     *
     * @param customerName the value for T_J_CUSTOMER_INFO.CUSTOMER_NAME
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_INFO.MARITAL_STATUS
     *
     * @return the value of T_J_CUSTOMER_INFO.MARITAL_STATUS
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public BigDecimal getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_INFO.MARITAL_STATUS
     *
     * @param maritalStatus the value for T_J_CUSTOMER_INFO.MARITAL_STATUS
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public void setMaritalStatus(BigDecimal maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_INFO.COUNTRY
     *
     * @return the value of T_J_CUSTOMER_INFO.COUNTRY
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_INFO.COUNTRY
     *
     * @param country the value for T_J_CUSTOMER_INFO.COUNTRY
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_INFO.NATIONALITY
     *
     * @return the value of T_J_CUSTOMER_INFO.NATIONALITY
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_INFO.NATIONALITY
     *
     * @param nationality the value for T_J_CUSTOMER_INFO.NATIONALITY
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_INFO.HEALTH
     *
     * @return the value of T_J_CUSTOMER_INFO.HEALTH
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public String getHealth() {
        return health;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_INFO.HEALTH
     *
     * @param health the value for T_J_CUSTOMER_INFO.HEALTH
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public void setHealth(String health) {
        this.health = health == null ? null : health.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_INFO.EDUCATION
     *
     * @return the value of T_J_CUSTOMER_INFO.EDUCATION
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_INFO.EDUCATION
     *
     * @param education the value for T_J_CUSTOMER_INFO.EDUCATION
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_INFO.NATIVE_LIVE_TIME
     *
     * @return the value of T_J_CUSTOMER_INFO.NATIVE_LIVE_TIME
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public Short getNativeLiveTime() {
        return nativeLiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_INFO.NATIVE_LIVE_TIME
     *
     * @param nativeLiveTime the value for T_J_CUSTOMER_INFO.NATIVE_LIVE_TIME
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public void setNativeLiveTime(Short nativeLiveTime) {
        this.nativeLiveTime = nativeLiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_INFO.TRADE_WORK_YEARS
     *
     * @return the value of T_J_CUSTOMER_INFO.TRADE_WORK_YEARS
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public Short getTradeWorkYears() {
        return tradeWorkYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_INFO.TRADE_WORK_YEARS
     *
     * @param tradeWorkYears the value for T_J_CUSTOMER_INFO.TRADE_WORK_YEARS
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public void setTradeWorkYears(Short tradeWorkYears) {
        this.tradeWorkYears = tradeWorkYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_INFO.CREATE_TIME
     *
     * @return the value of T_J_CUSTOMER_INFO.CREATE_TIME
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_INFO.CREATE_TIME
     *
     * @param createTime the value for T_J_CUSTOMER_INFO.CREATE_TIME
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_INFO.CREATE_USER
     *
     * @return the value of T_J_CUSTOMER_INFO.CREATE_USER
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_INFO.CREATE_USER
     *
     * @param createUser the value for T_J_CUSTOMER_INFO.CREATE_USER
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_INFO.UPDATE_TIME
     *
     * @return the value of T_J_CUSTOMER_INFO.UPDATE_TIME
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_INFO.UPDATE_TIME
     *
     * @param updateTime the value for T_J_CUSTOMER_INFO.UPDATE_TIME
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_INFO.UPDATE_USER
     *
     * @return the value of T_J_CUSTOMER_INFO.UPDATE_USER
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_INFO.UPDATE_USER
     *
     * @param updateUser the value for T_J_CUSTOMER_INFO.UPDATE_USER
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_INFO.ORG_CODE
     *
     * @return the value of T_J_CUSTOMER_INFO.ORG_CODE
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_INFO.ORG_CODE
     *
     * @param orgCode the value for T_J_CUSTOMER_INFO.ORG_CODE
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_INFO.CHANNEL_NAME
     *
     * @return the value of T_J_CUSTOMER_INFO.CHANNEL_NAME
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_INFO.CHANNEL_NAME
     *
     * @param channelName the value for T_J_CUSTOMER_INFO.CHANNEL_NAME
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_INFO.CHANNEL_CODE
     *
     * @return the value of T_J_CUSTOMER_INFO.CHANNEL_CODE
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public String getChannelCode() {
        return channelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_INFO.CHANNEL_CODE
     *
     * @param channelCode the value for T_J_CUSTOMER_INFO.CHANNEL_CODE
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public void setChannelCode(String channelCode) {
        this.channelCode = channelCode == null ? null : channelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_J_CUSTOMER_INFO.SALES_CHANNEL
     *
     * @return the value of T_J_CUSTOMER_INFO.SALES_CHANNEL
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public String getSalesChannel() {
        return salesChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_J_CUSTOMER_INFO.SALES_CHANNEL
     *
     * @param salesChannel the value for T_J_CUSTOMER_INFO.SALES_CHANNEL
     *
     * @mbggenerated Tue Mar 06 16:11:44 CST 2018
     */
    public void setSalesChannel(String salesChannel) {
        this.salesChannel = salesChannel == null ? null : salesChannel.trim();
    }
}